terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot access textfile textfiles/processes.txt
